# Generated by Django 4.2.18 on 2025-03-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelselectioncount',
            name='model_name',
            field=models.CharField(choices=[('model1', 'Gloss Model'), ('model2', 'Overlapping Model'), ('model3', 'OpenAI ChatGPT')], max_length=10, unique=True),
        ),
    ]
